apiVersion: v1
kind: Service
metadata:
  name: {{ include "azure-vote.backend.name" . }}
  labels:
    {{- include "azure-vote.labels" . | nindent 4 }}
    app: {{ include "azure-vote.backend.name" . }}
spec:
  ports:
  - port: {{ .Values.backend.service.port }}
  selector:
    app: {{ include "azure-vote.backend.name" . }}
