apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azure-vote.frontend.name" . }}
  labels:
    {{- include "azure-vote.labels" . | nindent 4 }}
    app: {{ include "azure-vote.frontend.name" . }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "azure-vote.frontend.name" . }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.frontend.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.frontend.strategy.rollingUpdate.maxUnavailable }}
  minReadySeconds: {{ .Values.frontend.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ include "azure-vote.frontend.name" . }}
    spec:
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "azure-vote.frontend.name" . }}
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
        {{- with .Values.frontend.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: REDIS
          value: {{ include "azure-vote.backend.name" . | quote }}
