apiVersion: v1
kind: Service
metadata:
  name: {{ include "azure-vote.frontend.name" . }}
  labels:
    {{- include "azure-vote.labels" . | nindent 4 }}
    app: {{ include "azure-vote.frontend.name" . }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
  selector:
    app: {{ include "azure-vote.frontend.name" . }}
